#pragma once

#include <vector>
#include <complex>
#include <string>
#include <fstream>
#include <iostream>
#include <cstdint>
#include <stdexcept>

using Complex = std::complex<double>;

/**
 * @brief Loader for MPS/MPO binary files generated by Python
 *
 * Reads binary files created by serialize_mps_mpo.py to ensure exact
 * reproducibility between CPU and GPU benchmarks.
 *
 * File format:
 * - MPS: num_sites, bond_dims[], phys_dims[], then for each site: shape[3], data[]
 * - MPO: num_sites, mpo_bond_dims[], phys_dims[], then for each site: shape[4], data[]
 *
 * All data is complex128 (std::complex<double>, 16 bytes per element).
 */

struct MPSTensor {
    int64_t D_left;   // Left bond dimension
    int64_t d;        // Physical dimension
    int64_t D_right;  // Right bond dimension
    std::vector<Complex> data;  // Size: D_left * d * D_right

    // Get element at (i, j, k)
    Complex& operator()(int64_t i, int64_t j, int64_t k) {
        return data[i * d * D_right + j * D_right + k];
    }

    const Complex& operator()(int64_t i, int64_t j, int64_t k) const {
        return data[i * d * D_right + j * D_right + k];
    }

    size_t total_elements() const {
        return D_left * d * D_right;
    }
};

struct MPOTensor {
    int64_t D_mpo_left;   // Left MPO bond dimension
    int64_t d_bra;        // Bra physical dimension
    int64_t d_ket;        // Ket physical dimension
    int64_t D_mpo_right;  // Right MPO bond dimension
    std::vector<Complex> data;  // Size: D_mpo_left * d_bra * d_ket * D_mpo_right

    // Get element at (i, j, k, l)
    Complex& operator()(int64_t i, int64_t j, int64_t k, int64_t l) {
        return data[i * d_bra * d_ket * D_mpo_right + j * d_ket * D_mpo_right + k * D_mpo_right + l];
    }

    const Complex& operator()(int64_t i, int64_t j, int64_t k, int64_t l) const {
        return data[i * d_bra * d_ket * D_mpo_right + j * d_ket * D_mpo_right + k * D_mpo_right + l];
    }

    size_t total_elements() const {
        return D_mpo_left * d_bra * d_ket * D_mpo_right;
    }
};

class MPSLoader {
public:
    /**
     * @brief Load MPS from binary file
     *
     * @param filepath Path to .bin file
     * @return Vector of MPS tensors (one per site)
     */
    static std::vector<MPSTensor> load(const std::string& filepath) {
        std::ifstream file(filepath, std::ios::binary);
        if (!file) {
            throw std::runtime_error("Failed to open MPS file: " + filepath);
        }

        // Read header
        int64_t num_sites;
        file.read(reinterpret_cast<char*>(&num_sites), sizeof(int64_t));

        if (num_sites <= 0 || num_sites > 10000) {
            throw std::runtime_error("Invalid num_sites: " + std::to_string(num_sites));
        }

        // Read bond dimensions (size: num_sites + 1)
        std::vector<int64_t> bond_dims(num_sites + 1);
        file.read(reinterpret_cast<char*>(bond_dims.data()), (num_sites + 1) * sizeof(int64_t));

        // Read physical dimensions (size: num_sites)
        std::vector<int64_t> phys_dims(num_sites);
        file.read(reinterpret_cast<char*>(phys_dims.data()), num_sites * sizeof(int64_t));

        // Read each tensor
        std::vector<MPSTensor> tensors(num_sites);

        for (int64_t site = 0; site < num_sites; ++site) {
            // Read shape (3 int64 values)
            int64_t shape[3];
            file.read(reinterpret_cast<char*>(shape), 3 * sizeof(int64_t));

            tensors[site].D_left = shape[0];
            tensors[site].d = shape[1];
            tensors[site].D_right = shape[2];

            // Validate
            if (tensors[site].D_left != bond_dims[site]) {
                throw std::runtime_error("Bond dimension mismatch at site " + std::to_string(site));
            }
            if (tensors[site].D_right != bond_dims[site + 1]) {
                throw std::runtime_error("Bond dimension mismatch at site " + std::to_string(site));
            }
            if (tensors[site].d != phys_dims[site]) {
                throw std::runtime_error("Physical dimension mismatch at site " + std::to_string(site));
            }

            // Read data
            size_t num_elements = tensors[site].total_elements();
            tensors[site].data.resize(num_elements);
            file.read(reinterpret_cast<char*>(tensors[site].data.data()),
                      num_elements * sizeof(Complex));
        }

        if (!file) {
            throw std::runtime_error("Error reading MPS file: " + filepath);
        }

        std::cout << "Loaded MPS from " << filepath << std::endl;
        std::cout << "  Sites: " << num_sites << std::endl;
        std::cout << "  Bond dims: [";
        for (size_t i = 0; i < bond_dims.size(); ++i) {
            std::cout << bond_dims[i];
            if (i < bond_dims.size() - 1) std::cout << ", ";
        }
        std::cout << "]" << std::endl;
        std::cout << "  Phys dims: [";
        for (size_t i = 0; i < phys_dims.size(); ++i) {
            std::cout << phys_dims[i];
            if (i < phys_dims.size() - 1) std::cout << ", ";
        }
        std::cout << "]" << std::endl;

        return tensors;
    }
};

class MPOLoader {
public:
    /**
     * @brief Load MPO from binary file
     *
     * @param filepath Path to .bin file
     * @return Vector of MPO tensors (one per site)
     */
    static std::vector<MPOTensor> load(const std::string& filepath) {
        std::ifstream file(filepath, std::ios::binary);
        if (!file) {
            throw std::runtime_error("Failed to open MPO file: " + filepath);
        }

        // Read header
        int64_t num_sites;
        file.read(reinterpret_cast<char*>(&num_sites), sizeof(int64_t));

        if (num_sites <= 0 || num_sites > 10000) {
            throw std::runtime_error("Invalid num_sites: " + std::to_string(num_sites));
        }

        // Read MPO bond dimensions (size: num_sites + 1)
        std::vector<int64_t> mpo_bond_dims(num_sites + 1);
        file.read(reinterpret_cast<char*>(mpo_bond_dims.data()), (num_sites + 1) * sizeof(int64_t));

        // Read physical dimensions (size: num_sites)
        std::vector<int64_t> phys_dims(num_sites);
        file.read(reinterpret_cast<char*>(phys_dims.data()), num_sites * sizeof(int64_t));

        // Read each tensor
        std::vector<MPOTensor> tensors(num_sites);

        for (int64_t site = 0; site < num_sites; ++site) {
            // Read shape (4 int64 values)
            int64_t shape[4];
            file.read(reinterpret_cast<char*>(shape), 4 * sizeof(int64_t));

            tensors[site].D_mpo_left = shape[0];
            tensors[site].d_bra = shape[1];
            tensors[site].d_ket = shape[2];
            tensors[site].D_mpo_right = shape[3];

            // Validate
            if (tensors[site].D_mpo_left != mpo_bond_dims[site]) {
                throw std::runtime_error("MPO bond dimension mismatch at site " + std::to_string(site));
            }
            if (tensors[site].D_mpo_right != mpo_bond_dims[site + 1]) {
                throw std::runtime_error("MPO bond dimension mismatch at site " + std::to_string(site));
            }
            if (tensors[site].d_bra != phys_dims[site] || tensors[site].d_ket != phys_dims[site]) {
                throw std::runtime_error("Physical dimension mismatch at site " + std::to_string(site));
            }

            // Read data
            size_t num_elements = tensors[site].total_elements();
            tensors[site].data.resize(num_elements);
            file.read(reinterpret_cast<char*>(tensors[site].data.data()),
                      num_elements * sizeof(Complex));
        }

        if (!file) {
            throw std::runtime_error("Error reading MPO file: " + filepath);
        }

        std::cout << "Loaded MPO from " << filepath << std::endl;
        std::cout << "  Sites: " << num_sites << std::endl;
        std::cout << "  MPO bond dims: [";
        for (size_t i = 0; i < mpo_bond_dims.size(); ++i) {
            std::cout << mpo_bond_dims[i];
            if (i < mpo_bond_dims.size() - 1) std::cout << ", ";
        }
        std::cout << "]" << std::endl;
        std::cout << "  Phys dims: [";
        for (size_t i = 0; i < phys_dims.size(); ++i) {
            std::cout << phys_dims[i];
            if (i < phys_dims.size() - 1) std::cout << ", ";
        }
        std::cout << "]" << std::endl;

        return tensors;
    }
};
